### PR TITLE
Updates to add stat citations

### PR DESCRIPTION
**Pull request by magreen521**
Website issue: https://github.com/angelshot/angelshot.ltd/issues/39

about-us.js: 
-Added div with citations in MLA format
-Added superscripts for associated citations

about-us.module.css: 
-Added CSS for the citations div

cardWithOverlay.module.css:
-Added CSS rules for superscript links

### CODE REVIEW

**Comment by magreen521** [comment]
In the first commit, I added the import statement for the Card component since I originally planned to use it for the citations. I ended up using a div instead, so the new commit is to remove the leftover import statement for the Card.

**Comment by nub4life** [comment]
1. The hover on the citation numbers are lost when you hover over them on desktop.
2. Move citations up to right above Milestones section
3. Reduce font size of citations to `font-size:smaller`
4. Remove white background from citations section
5. Superscript numbers should be smaller.
6. Please make the URLs clickable (open in a new window)

**Review by nub4life — CHANGES_REQUESTED** [review]
Please see my comments. Thanks!

**Comment by sidnny** [comment]
Visual reference for Wendy's comments:
citations

For the superscript you can use
`.sup {
    font: 12px/1 droid-serif,serif;
}`

**Review by sidnny — DISMISSED** [review]
Visual reference for Wendy's comments:
citations

For the superscript you can use
`.sup {
    font: 12px/1 droid-serif,serif;
}`

**Review by nub4life — APPROVED** [review]

**Pull request merged**
